### ISSUE TITLE
Unable to start gnome-twofactorauth

### ISSUE THREAD

**Issue by kennethdhau** [bil-elmoussaoui/Gnome-TwoFactorAuth#12]
System info:

> Python 3.5.1
> GTK3 3.20.6-1
> Installed via gnome-twofactorauth-git
> Arch linux 4.6.2-1 | cinnamon 3.0.5

Presented error:

> Traceback (most recent call last):
>   File "/usr/lib/python3.5/site-packages/TwoFactorAuth/application.py", line 99, in do_activate
>     self.win = Window(self)
>   File "/usr/lib/python3.5/site-packages/TwoFactorAuth/widgets/window.py", line 40, in __init__
>     self.refresh_window()
>   File "/usr/lib/python3.5/site-packages/TwoFactorAuth/widgets/window.py", line 319, in refresh_window
>     self.hb.refresh()
>   File "/usr/lib/python3.5/site-packages/TwoFactorAuth/widgets/headerbar.py", line 188, in refresh
>     self.toggle_settings_button(True)
>   File "/usr/lib/python3.5/site-packages/TwoFactorAuth/widgets/headerbar.py", line 144, in toggle_settings_button
>     self.lock_bsettings_buttonutton.set_no_show_all(not visible)
> AttributeError: 'HeaderBar' object has no attribute 'lock_bsettings_buttonutton'

Attempted solutions:

Reinstallation of gtk3
Reinstallation of gnome-twofactorauth-git
Installation of gnome-twofactorauth

**Comment by bil-elmoussaoui** [comment]
Thanks for the report! It's an easy fix, i will push the fix with some other modifications soon :+1:
