### ISSUE TITLE
Unable to access Settings menu

### ISSUE THREAD

**Issue by kennethdhau** [bil-elmoussaoui/Gnome-TwoFactorAuth#13]
I clicked "cancel" during the initial keyring password creation which has set my access password to an empty string as well as seemingly prevented me from accessing the settings menu.  Further, it seems during prompts for password creation, all other resources are blocked i.e. I cannot use the terminal, all GUIs non-responsive.

**Comment by bil-elmoussaoui** [comment]
The keyring password is used to encrypt the secret codes and not to lock/unlock the application. What you can do is use DConf editor and go to org.gnome.TwoFactorAuth.login and change the state to false, and the password to an empty string, reopen the application again

**Comment by kennethdhau** [comment]
Is there a way to set the keyring password? At the moment, org.gnome.TwoFactorAuth.login is in plaintext.

**Comment by bil-elmoussaoui** [comment]
You can try using Seahorse (a gui to manage keyring storage) and remove the TwoFactorAuth folder. Once you open the application, the "folder" will be created again and you will be asked to choose a password; 
What do you mean by a plaintext? can you share a screenshot?

**Comment by kennethdhau** [comment]
![screenshot from 2016-06-19 13-37-21](https://cloud.githubusercontent.com/assets/11970451/16178892/0f4e51b0-3623-11e6-88a7-ba6391f851f6.png)

**Comment by kennethdhau** [comment]
This was actually done in reverse. I set the password and used it to access the TwoFactorAuth client

**Comment by bil-elmoussaoui** [comment]
You must encrypt the password using sha256; storing the plain text directly would be too easy for someone to access to the application and connect to your accounts:)

**Comment by kennethdhau** [comment]
I deleted the TwoFactorAuth folder from Seahorse but I'm still not prompted for a new keyring password

**Comment by bil-elmoussaoui** [comment]
@kennethdhau https://askubuntu.com/questions/65281/how-to-recover-reset-forgotten-gnome-keyring-password

**Comment by kennethdhau** [comment]
I've cleared the folder under Seahorse. It prompted for a new keyring password, which I've set. I believe these are now working thusfar.
org.gnome.TwoFactorAuth.login, the credentials for opening the client, still seem to be in plaintext, although I may just go about with keeping the password disabled.  Also, I'm still having trouble accessing the settings panel.

**Comment by bil-elmoussaoui** [comment]
Well, reset the password to the default value (using dconf editor) the same for the state. And enable using the settings. 
Can you tell me which distro/desktop are you using?

**Comment by bil-elmoussaoui** [comment]
I think i've fixed the settings menu in the latest git update, can you try it?

**Comment by kennethdhau** [comment]
I'm on Arch Linux (4.6.2-1) on Cinnamon 3.0.5. The settings menu does appear and it seems setting the password does work.  However, while changing the password requires the true password, the interface will allow me to enter the value I manually enter into org.gnome.TwoFactorAuth.login. i.e. if my password is "hello" (hashing to 2cf2...9824), I can enter "hello" or the hash to access the application.

**Comment by bil-elmoussaoui** [comment]
I will fix that soon in my next commit :+1:

**Comment by bil-elmoussaoui** [comment]
Fixed your latest issue. If you have any ideas/issues please open an other issue! Thanks
