### ISSUE TITLE
How to create an account for Twitch

### ISSUE THREAD

**Issue by ckorn** [bil-elmoussaoui/Gnome-TwoFactorAuth#14]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.18.9
 * Desktop environment - Unity
 ```

**Gnome TwoFactorAuth version**
0.1

**Actual issue**
When adding an account for twitch there is a secret code I should enter, but I don't know what code that is.

**Steps to reproduce (if you knew)**
Try to create an account for Twitch and feel confused.

**Other Note (feature-request, question, etc...)**
Maybe I get it wrong, and the accounts are just a list of sites which support 2FA in *any* way.
But this way might not necessarily be supported by GNOME-2FA. If that's the case then please filter the list accordingly.

**Comment by bil-elmoussaoui** [comment]
The secret code that you should enter is the one you get from the website(twitch in your case) when you enable 2FA. It's either a code or a QR code, you can scan the QR code too using the Gnome-2FA.
The list of sites are the sites that support 2FA using an application (in this case Gnome-2FA), as they can support it by sending the code by SMS or by a call;
Hope it's clear enough now

**Comment by ckorn** [comment]
Well, when activating 2FA on twitch they ask for my mobile number and send me a seven digit code by SMS. But GNOME-2FA does not accept this code.

**Comment by bil-elmoussaoui** [comment]
I use the database from this site https://twofactorauth.org/ and as you can see Twitch supports software 2FA tokens too. Do you know if there's an application that provide twitch support ? so i can take a look how they do that? =)
![capture du 2016-06-28 02-31-02](https://cloud.githubusercontent.com/assets/7660997/16400065/615cbcce-3cd8-11e6-9b77-8418303a37b7.png)

**Comment by ckorn** [comment]
Thanks for your answer. Twitch makes use of Authy which I already installed on my phone and it works well. I just thought GNOME-2FA would be an app which supports all 2FA sites no matter how they do it.
So I think Twitch (and probably other sites) should not be listed in GNOME-2FA because it cannot handle it.

**Comment by bil-elmoussaoui** [comment]
@ckorn Can you report that [here](https://github.com/2factorauth/twofactorauth). As i use their database instead of providing my own? so they can take care of that. 
Btw, i think Twitch use Authy API to directly add your twitch account to it... I will see if i can implement Authy sync later.
Thanks!
Closing this as i can't do anything about it.
